<?php 

return [
    'actions' => [
        'user_add',
        'user_update',
        'user_add_documents',
        'user_delete_documents',
        'user_delete',
        'user_approved',
        'user_unapproved',
        'create_merchants_outstanding_report',
        'create_bill_report',
        'create_transfer',
        'create_channel',
        'update_channel',
        'delete_channel',
        'create_role',
        'update_role',
        'delete_role',
        'create_user',
        'update_user',
        'delete_user',
        'restore_user',
        'force_delete_user',
        'accept_transfer',
        'reject_transfer',
        'send_to_sps',
        'update_general_setting',
        'create_bank',
        'update_bank',
        'delete_bank',
        'update_tax_invoice_request',
    ],
];